from typing import List, Tuple
from dataclasses import dataclass, astuple


@dataclass
class TestCaseItem:
    name: str
    shapes_path: str
    valid_data_path: str
    invalid_data_path: str
    expected_failures: int

    def astuple(self) -> Tuple:
        return astuple(self)


test_cases: List[TestCaseItem] = [
    TestCaseItem(
        name="plot-description-structural-formation",
        shapes_path="shapes/plot-description-protocol-shapes/structural-formation/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/structural-formation/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/structural-formation/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-slope-class",
        shapes_path="shapes/plot-description-protocol-shapes/slope-class/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/slope-class/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/slope-class/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-height-class",
        shapes_path="shapes/plot-description-protocol-shapes/height-class/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/height-class/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/height-class/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-homogeneity-measure",
        shapes_path="shapes/plot-description-protocol-shapes/homogeneity-measure/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/homogeneity-measure/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/homogeneity-measure/invalid.ttl",
        expected_failures=8,
    ).astuple(),
    TestCaseItem(
        name="plot-description-surface-strew-size",
        shapes_path="shapes/plot-description-protocol-shapes/surface-strew-size/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/surface-strew-size/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/surface-strew-size/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-landform-pattern",
        shapes_path="shapes/plot-description-protocol-shapes/landform-pattern/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/landform-pattern/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/landform-pattern/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-rock-outcrop-lithology",
        shapes_path="shapes/plot-description-protocol-shapes/rock-outcrop-lithology/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/rock-outcrop-lithology/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/rock-outcrop-lithology/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-cover",
        shapes_path="shapes/plot-description-protocol-shapes/cover/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/cover/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/cover/invalid.ttl",
        expected_failures=8,
    ).astuple(),
    TestCaseItem(
        name="plot-description-disturbance-type",
        shapes_path="shapes/plot-description-protocol-shapes/disturbance-type/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/disturbance-type/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/disturbance-type/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-surface-strew-lithology",
        shapes_path="shapes/plot-description-protocol-shapes/surface-strew-lithology/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/surface-strew-lithology/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/surface-strew-lithology/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-second-dominant-species",
        shapes_path="shapes/plot-description-protocol-shapes/second-dominant-species/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/second-dominant-species/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/second-dominant-species/invalid.ttl",
        expected_failures=6,
    ).astuple(),
    TestCaseItem(
        name="plot-description-landform-element",
        shapes_path="shapes/plot-description-protocol-shapes/landform-element/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/landform-element/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/landform-element/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-slope",
        shapes_path="shapes/plot-description-protocol-shapes/slope/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/slope/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/slope/invalid.ttl",
        expected_failures=8,
    ).astuple(),
    TestCaseItem(
        name="plot-description-fire-history",
        shapes_path="shapes/plot-description-protocol-shapes/fire-history/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/fire-history/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/fire-history/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-growth-form",
        shapes_path="shapes/plot-description-protocol-shapes/growth-form/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/growth-form/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/growth-form/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-climatic-condition",
        shapes_path="shapes/plot-description-protocol-shapes/climatic-condition/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/climatic-condition/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/climatic-condition/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-growth-stage",
        shapes_path="shapes/plot-description-protocol-shapes/growth-stage/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/growth-stage/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/growth-stage/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-third-dominant-species",
        shapes_path="shapes/plot-description-protocol-shapes/third-dominant-species/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/third-dominant-species/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/third-dominant-species/invalid.ttl",
        expected_failures=6,
    ).astuple(),
    TestCaseItem(
        name="plot-description-aspect",
        shapes_path="shapes/plot-description-protocol-shapes/aspect/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/aspect/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/aspect/invalid.ttl",
        expected_failures=8,
    ).astuple(),
    TestCaseItem(
        name="plot-description-cover-class",
        shapes_path="shapes/plot-description-protocol-shapes/cover-class/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/cover-class/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/cover-class/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="plot-description-dominant-species",
        shapes_path="shapes/plot-description-protocol-shapes/dominant-species/shapes.ttl",
        valid_data_path="shapes/plot-description-protocol-shapes/dominant-species/valid.ttl",
        invalid_data_path="shapes/plot-description-protocol-shapes/dominant-species/invalid.ttl",
        expected_failures=6,
    ).astuple(),
    TestCaseItem(
        name="cover-full-growth-form",
        shapes_path="shapes/cover/cover-full-protocol-shapes/growth-form/shapes.ttl",
        valid_data_path="shapes/cover/cover-full-protocol-shapes/growth-form/valid.ttl",
        invalid_data_path="shapes/cover/cover-full-protocol-shapes/growth-form/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="cover-full-field-species-name",
        shapes_path="shapes/cover/cover-full-protocol-shapes/field-species-name/shapes.ttl",
        valid_data_path="shapes/cover/cover-full-protocol-shapes/field-species-name/valid.ttl",
        invalid_data_path="shapes/cover/cover-full-protocol-shapes/field-species-name/invalid.ttl",
        expected_failures=6,
    ).astuple(),
    TestCaseItem(
        name="cover-full-substrate-type",
        shapes_path="shapes/cover/cover-full-protocol-shapes/substrate-type/shapes.ttl",
        valid_data_path="shapes/cover/cover-full-protocol-shapes/substrate-type/valid.ttl",
        invalid_data_path="shapes/cover/cover-full-protocol-shapes/substrate-type/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="cover-full-uppermost-height",
        shapes_path="shapes/cover/cover-full-protocol-shapes/uppermost-height/shapes.ttl",
        valid_data_path="shapes/cover/cover-full-protocol-shapes/uppermost-height/valid.ttl",
        invalid_data_path="shapes/cover/cover-full-protocol-shapes/uppermost-height/invalid.ttl",
        expected_failures=8,
    ).astuple(),
    TestCaseItem(
        name="cover-full-in-canopy-sky",
        shapes_path="shapes/cover/cover-full-protocol-shapes/in-canopy-sky/shapes.ttl",
        valid_data_path="shapes/cover/cover-full-protocol-shapes/in-canopy-sky/valid.ttl",
        invalid_data_path="shapes/cover/cover-full-protocol-shapes/in-canopy-sky/invalid.ttl",
        expected_failures=6,
    ).astuple(),
    TestCaseItem(
        name="cover-lite-growth-form",
        shapes_path="shapes/cover/cover-lite-protocol-shapes/growth-form/shapes.ttl",
        valid_data_path="shapes/cover/cover-lite-protocol-shapes/growth-form/valid.ttl",
        invalid_data_path="shapes/cover/cover-lite-protocol-shapes/growth-form/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="cover-lite-field-species-name",
        shapes_path="shapes/cover/cover-lite-protocol-shapes/field-species-name/shapes.ttl",
        valid_data_path="shapes/cover/cover-lite-protocol-shapes/field-species-name/valid.ttl",
        invalid_data_path="shapes/cover/cover-lite-protocol-shapes/field-species-name/invalid.ttl",
        expected_failures=6,
    ).astuple(),
    TestCaseItem(
        name="cover-lite-substrate-type",
        shapes_path="shapes/cover/cover-lite-protocol-shapes/substrate-type/shapes.ttl",
        valid_data_path="shapes/cover/cover-lite-protocol-shapes/substrate-type/valid.ttl",
        invalid_data_path="shapes/cover/cover-lite-protocol-shapes/substrate-type/invalid.ttl",
        expected_failures=7,
    ).astuple(),
    TestCaseItem(
        name="cover-lite-uppermost-height",
        shapes_path="shapes/cover/cover-lite-protocol-shapes/uppermost-height/shapes.ttl",
        valid_data_path="shapes/cover/cover-lite-protocol-shapes/uppermost-height/valid.ttl",
        invalid_data_path="shapes/cover/cover-lite-protocol-shapes/uppermost-height/invalid.ttl",
        expected_failures=8,
    ).astuple(),
    TestCaseItem(
        name="cover-lite-in-canopy-sky",
        shapes_path="shapes/cover/cover-lite-protocol-shapes/in-canopy-sky/shapes.ttl",
        valid_data_path="shapes/cover/cover-lite-protocol-shapes/in-canopy-sky/valid.ttl",
        invalid_data_path="shapes/cover/cover-lite-protocol-shapes/in-canopy-sky/invalid.ttl",
        expected_failures=6,
    ).astuple(),
]
