= Ecological Data Exchange Specification (working title)
:toc: left
:toclevels: 4
:table-stripes: even
:sectnums:
:sectnumlevels: 5
:sectlinks:
:icons: font
:favicon: https://www.tern.org.au/wp-content/uploads/2019/10/favicon.png
:idprefix:

NOTE: *Status: Draft* - while the document is in draft, sections of the document may contain placheholders such as `TBA` and `TBD`. 

== Metadata

[frame=none, grid=none, cols="1s,5"]
|===
|IRI | `https://linked.data.gov.au/def/rlp/spec` (`TBC`)
|Title | Ecological Data Exchange Specification (working title)
|Definition | This document lists the normative requirements for data aiming to conform to the TERN Ecosystem Surveillance Ecological Monitoring Protocols. It is to be used as the authoritative, human-readable list of individual requirements from which profile artefacts such as validators are derived from.
|Created | 2022-03-14
|Modified | 2022-03-14
|Creator | link:https://linked.data.gov.au/org/tern[TERN]
|Publisher | link:https://linked.data.gov.au/org/dawe[Department of Agriculture, Water and the Environment]
|License | link:https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International (CC BY 4.0)]
|Further information | This document is part of the Services Agreement for the provision of standardised ecological monitoring protocols and systems for data collection, storage and management.

Procurement Number (PRN): 360 000 5101

Commonwealth of Australia as represented by the Department of Agriculture, Water and the Environment +
ABN 34 190 894 983 (*Department*)

The University of Queensland as represented by TERN +
ABN 63 942 912 684 (*Service Provider*)
|*Alternate document formats* | link:https://ternaustralia.github.io/dawe-rlp-spec/spec.pdf[PDF]
|===

== Preamble

=== Abstract

TERN Ecosystem Surveillance have developed 19 modules to standardise ecological monitoring protocols for data collection. The working title for the monitoring protocols is _TERN Ecosystem Surveillance Ecological Monitoring Protocols_.

TERN Data Services and Analytics is developing a standardised data exchange specification to support the exchange of data collected using TERN Ecosystem Surveillance Ecological Monitoring Protocols. The working title for the data exchange specification is _Ecological Data Exchange Specification_.

The Ecological Data Exchange Specification is a profile of the ecological data model known as the link:https://linkeddata.tern.org.au/information-models/tern-ontology[TERN Ontology]. Data that is conformant to the Ecological Data Exchange Specification is also conformant to the TERN Ontology.

=== Normative Status

This specification is normative for the exchange of data collected using TERN Ecosystem Surveillance Ecological Monitoring Protocols.

include::standard-parts.adoc[]

include::namespaces.adoc[]

include::requirements.adoc[]

include::editors-notes.adoc[]