== Requirements

=== Domain Model Conformance

Requirements define the rules and constraints which data must conform to in order to be valid.

A _status_ is assigned to each requirement. The _status_ code used in this document is defined by the link:http://purl.org/linked-data/registry[Registry ontology] and a subset of the status codes are used and redefined here:

* `*submitted*` - A proposed entry which is not yet approved for use for use. Corresponds to ISO 19135:(redraft) 'submitted'.
* `*invalid*` - An entry which has been invalidated due to serious flaws, distinct from retrirement. Corresponds to ISO 19135(redraft) 'invalid'.
* `*stable*` - An entry that is seen as having a reasonable measure of stability, may be used to mark the full adoption of a previously 'experimental' entry.

Requirements that have been accepted and are *stable* are marked with a green check mark.

For example:

[frame=none, cols="1,5"]
|===
|Property | Value

include::statuses/stable.adoc[]
|===

include::requirements-sections.adoc[]

=== TERN Ontology Conformance

`TBD`.
