name: Build and deploy specification document to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install asciidoctor
        run: apt-get install -y asciidoctor

      - name: Build asciidoc files
        run: asciidoctor --trace -a stylesheet=docs/source/styles.css -o build/index.html docs/source/index.adoc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
